/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDeviceCompleteRouteImport } from './routes/api/public/device/complete'
import { Route as ApiPublicDeviceTransactionRouteImport } from './routes/api/public/device/transaction'
import { Route as ApiPublicDeviceStatusIdRouteImport } from './routes/api/public/device/status.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceCompleteRoute = ApiPublicDeviceCompleteRouteImport.update({
  id: '/api/public/device/complete',
  path: '/api/public/device/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceTransactionRoute =
  ApiPublicDeviceTransactionRouteImport.update({
    id: '/api/public/device/transaction',
    path: '/api/public/device/transaction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeviceStatusIdRoute = ApiPublicDeviceStatusIdRouteImport.update({
  id: '/api/public/device/status/$id',
  path: '/api/public/device/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/device/complete': typeof ApiPublicDeviceCompleteRoute
  '/api/public/device/transaction': typeof ApiPublicDeviceTransactionRoute
  '/api/public/device/status/$id': typeof ApiPublicDeviceStatusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/device/complete': typeof ApiPublicDeviceCompleteRoute
  '/api/public/device/transaction': typeof ApiPublicDeviceTransactionRoute
  '/api/public/device/status/$id': typeof ApiPublicDeviceStatusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/device/complete': typeof ApiPublicDeviceCompleteRoute
  '/api/public/device/transaction': typeof ApiPublicDeviceTransactionRoute
  '/api/public/device/status/$id': typeof ApiPublicDeviceStatusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/device/complete'
    | '/api/public/device/transaction'
    | '/api/public/device/status/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/device/complete'
    | '/api/public/device/transaction'
    | '/api/public/device/status/$id'
  id:
    | '__root__'
    | '/'
    | '/api/public/device/complete'
    | '/api/public/device/transaction'
    | '/api/public/device/status/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDeviceCompleteRoute: typeof ApiPublicDeviceCompleteRoute
  ApiPublicDeviceTransactionRoute: typeof ApiPublicDeviceTransactionRoute
  ApiPublicDeviceStatusIdRoute: typeof ApiPublicDeviceStatusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/complete': {
      id: '/api/public/device/complete'
      path: '/api/public/device/complete'
      fullPath: '/api/public/device/complete'
      preLoaderRoute: typeof ApiPublicDeviceCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/transaction': {
      id: '/api/public/device/transaction'
      path: '/api/public/device/transaction'
      fullPath: '/api/public/device/transaction'
      preLoaderRoute: typeof ApiPublicDeviceTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/status/$id': {
      id: '/api/public/device/status/$id'
      path: '/api/public/device/status/$id'
      fullPath: '/api/public/device/status/$id'
      preLoaderRoute: typeof ApiPublicDeviceStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDeviceCompleteRoute: ApiPublicDeviceCompleteRoute,
  ApiPublicDeviceTransactionRoute: ApiPublicDeviceTransactionRoute,
  ApiPublicDeviceStatusIdRoute: ApiPublicDeviceStatusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
